### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by zxqSled** [nuaa-nlp/Character100#1]
hello~,I am very interested in this great work,but I fail to follow this work due to my weak skills,could you give me some suggestions~
   1.could you please give the "requirements.txt",i meet the error"ImportError: cannot import name 'DiscriminatorEvalDataset' from 'dataset'",is this the version issue
   2.how to use the "dev.json、train.json" to train the llm,could you give me a demo
   3.what's the meaning of "metric_path" in "background_knowledge.py" and where to get the "predict_path and truth_path"
   4.how can i follow the part of "zero-shot and few-shot" of experiment
Looking forword to your reply!!!!thanks very much~~

**Comment by Infinity4B** [comment]
Hi, sorry for the late reply.

1. We have updated the environment needed for this repository [here](https://github.com/nuaa-nlp/Character100#environments).
2. The `train.json` and `dev.json` are simply input pairs and are easy to follow. As different models may be trained differently, you can implement your own dataset class.
3. We have removed `metric_path` here as it is not needed. The `predict_path` and `truth_path` stands for the file for the predicted results by the model and the ground truth. Each line in the file stands for a predicted response/ground truth response.
4. The example of getting zero-shot data and few-shot data is provided in `Code/dataset_example.py`. You can refer to it to get more details.

Feel free to reopen the issue if you have any questions.
